### PR TITLE
Fix for newer versions of AnnData

### PR DESCRIPTION
**Pull request by milescsmith**
Since version [version 0.7.2](https://anndata.readthedocs.io/en/latest/#id1), anndata objects store their connectivity data in the `.obsp['neighbors']` instead of in `.uns['neighbors']['connectivities']`.  The latter location, however, is where `cna.tools_nam. diffuse_stepwise()` looks for the data, causing `cna` to fail on newer anndata objects.  I've added a bit so that `diffuse_stepwise()` will check version and adjust its behavior accordingly.

### CODE REVIEW

**Comment by yakirr** [comment]
Thanks for this thoughtful update! Looks like you also brought our coding and packaging conventions up to snuff, which we appreciate. Because there are several changes, it may take us some time to merge this pull request but we will likely do so -- appreciatively.

(making sure @rumker sees this as well)

**Comment by milescsmith** [comment]
No problem!  Thanks for the great package!  Let me know if there's anything I need to change or can help with.

**Comment by yakirr** [comment]
@milescsmith, a few other issues are precluding us from having the bandwidth to look at the packaging-related changes in this pull request. But we'd like to not delay anymore on accepting the scanpy-related changes! Any chance we could ask you to make a separate pull request just for the scanpy version-related change that we could then accept more quickly? And then we could come back to the packaging-related stuff in a few weeks most likely.

**Comment by yakirr** [comment]
Hi @milescsmith we wanted to ping you again about splitting out the scanpy compatibility fix as a separate pull request.

Ideally, there would actually be three separate pull requests here: 1) scanpy compatibility, 2) package management changes, and 3) formatting changes for PEP compliance. This would allow us to review each set of semantic changes separately, and to review semantic changes separately from formatting changes.

If you're short on time, we'd prioritize (1) over (2) or (3) so just that one would be great to have you split out as a separate pull request.

Thank you again for contributing to our project!

**Comment by milescsmith** [comment]
Hey, sorry for the silence - I happened to off on vacation.

Splitting those changes up into three pull requests shouldn't be too difficult or time consuming.  I'll close this one out and create those others in its place.

**Pull request closed without merging**
